export type Employee = {
    id: string;
    firstName: string;
    lastName: string;
    email: string;
    role: string;
    department: string;
    status: 'Active' | 'On Leave' | 'Terminated';
    avatar?: string;
    joinedDate: string;
    dateOfBirth?: string;
    gender?: string;
    maritalStatus?: string;
    phone?: string;
    address?: string;
    bankName?: string;
    accountNumber?: string;
    salary?: number;
    emergencyContactName?: string;
    emergencyContactRel?: string;
    emergencyContactPhone?: string;
    directManagerId?: string;
    indirectManagerId?: string;
    contractRenewalDate?: string;
    nationality?: 'Saudi' | 'Egyptian' | 'Other';
    isGosiApplicable?: boolean;
    isTaxApplicable?: boolean;
    currency?: 'SAR' | 'EGP' | 'USD';
    personalEmail?: string;
    housingAllowance?: number;
    transportationAllowance?: number;
    otherAllowance?: number;
    laptopAllowance?: number;
    overtime?: number;
    bonus?: number;
};

export const employees: Employee[] = [
    {
        id: "1",
        firstName: "Abdulmosen",
        lastName: "AlQaud",
        email: "abdulmosen.alqaud@superhr.com",
        role: "CEO",
        department: "Executive",
        status: "Active",
        joinedDate: "2020-01-15",
        nationality: "Saudi",
        isGosiApplicable: true,
        isTaxApplicable: false,
        currency: "SAR",
        salary: 150000,
        housingAllowance: 2500,
        transportationAllowance: 1000,
        otherAllowance: 500,
        laptopAllowance: 200,
    },
    {
        id: "2",
        firstName: "Ahmed",
        lastName: "Kammorah",
        email: "ahmed.kammorah@superhr.com",
        role: "CTO",
        department: "Engineering",
        status: "Active",
        joinedDate: "2020-03-10",
        nationality: "Egyptian",
        isGosiApplicable: false,
        isTaxApplicable: true,
        currency: "USD",
        salary: 9000,
        housingAllowance: 0,
        transportationAllowance: 0,
        otherAllowance: 0,
        laptopAllowance: 0,
        overtime: 0,
        bonus: 0,
    },
    {
        id: "3",
        firstName: "Rania",
        lastName: "Mohamed",
        email: "rania.mohamed@superhr.com",
        role: "VP of People",
        department: "HR",
        status: "Active",
        joinedDate: "2021-02-20",
        nationality: "Egyptian",
        currency: "EGP",
        salary: 35000,
        isGosiApplicable: false,
        isTaxApplicable: true,
    },
    {
        id: "4",
        firstName: "Ahmed",
        lastName: "Amr",
        email: "ahmed.amr@superhr.com",
        role: "Senior Software Engineer",
        department: "Engineering",
        status: "Active",
        joinedDate: "2022-05-11",
        nationality: "Egyptian",
        isGosiApplicable: false,
        isTaxApplicable: true,
        currency: "USD",
        salary: 22000,
        housingAllowance: 5000,
        transportationAllowance: 2000,
    },
    {
        id: "5",
        firstName: "Weam",
        lastName: "Khouj",
        email: "weam.khouj@superhr.com",
        role: "Product Manager",
        department: "Product",
        status: "Active",
        joinedDate: "2021-11-05",
        nationality: "Saudi",
        currency: "SAR",
        salary: 18000,
        isGosiApplicable: true,
        isTaxApplicable: false,
    },
    {
        id: "6",
        firstName: "Mohamed",
        lastName: "Mostafa",
        email: "mohamed.mostafa@superhr.com",
        role: "Lead Designer",
        department: "Design",
        status: "Active",
        joinedDate: "2022-01-08",
        currency: "USD",
        salary: 16000,
    },
    {
        id: "7",
        firstName: "Ahmed",
        lastName: "Gamal",
        email: "ahmed.gamal@superhr.com",
        role: "DevOps Engineer",
        department: "Engineering",
        status: "Active",
        joinedDate: "2022-08-14",
        currency: "USD",
        salary: 17500,
    },
    {
        id: "8",
        firstName: "Mohamed",
        lastName: "Ali",
        email: "mohamed.ali@superhr.com",
        role: "Data Scientist",
        department: "Engineering",
        status: "Active",
        joinedDate: "2023-01-22",
        currency: "USD",
        salary: 15500,
    },
    {
        id: "9",
        firstName: "Noha",
        lastName: "Alshreef",
        email: "noha.alshreef@superhr.com",
        role: "HR Specialist",
        department: "HR",
        status: "Active",
        joinedDate: "2023-03-15",
        currency: "SAR",
        salary: 12000,
    },
    {
        id: "10",
        firstName: "Yusuf",
        lastName: "Abd El-Nabi",
        email: "yusuf.abdelnabi@superhr.com",
        role: "Frontend Engineer",
        department: "Engineering",
        status: "Active",
        joinedDate: "2023-04-10",
        currency: "USD",
        salary: 14000,
    },
    {
        id: "11",
        firstName: "Sara",
        lastName: "Humaidi",
        email: "sara.humaidi@superhr.com",
        role: "Marketing Manager",
        department: "Marketing",
        status: "Active",
        joinedDate: "2022-09-01",
        currency: "SAR",
        salary: 13500,
    },
    {
        id: "12",
        firstName: "Ahmed",
        lastName: "Alaa Eldin",
        email: "ahmed.alaa@superhr.com",
        role: "Backend Engineer",
        department: "Engineering",
        status: "Active",
        joinedDate: "2023-02-18",
        currency: "USD",
        salary: 14500,
    },
    {
        id: "13",
        firstName: "Sami",
        lastName: "Mashaal",
        email: "sami.mashaal@superhr.com",
        role: "Sales Director",
        department: "Sales",
        status: "Active",
        joinedDate: "2021-07-22",
        currency: "USD",
        salary: 28000,
    },
    {
        id: "14",
        firstName: "Hamed",
        lastName: "Mostufa",
        email: "hamed.mostufa@superhr.com",
        role: "Account Executive",
        department: "Sales",
        status: "Active",
        joinedDate: "2022-12-05",
        currency: "USD",
        salary: 11000,
    },
    {
        id: "15",
        firstName: "Mohamed",
        lastName: "Abdelmaksoud",
        email: "mohamed.abdelmaksoud@superhr.com",
        role: "QA Engineer",
        department: "Engineering",
        status: "Active",
        joinedDate: "2023-05-11",
        currency: "USD",
        salary: 12500,
    },
    {
        id: "16",
        firstName: "Sameh",
        lastName: "Reda",
        email: "sameh.reda@superhr.com",
        role: "UX Researcher",
        department: "Design",
        status: "Active",
        joinedDate: "2022-10-10",
        currency: "USD",
        salary: 13000,
    },
    {
        id: "17",
        firstName: "Abdulaziz",
        lastName: "Alsalman",
        email: "abdulaziz.alsalman@superhr.com",
        role: "Financial Analyst",
        department: "Finance",
        status: "Active",
        joinedDate: "2021-06-15",
        nationality: "Saudi",
        currency: "SAR",
        salary: 19000,
        isGosiApplicable: true,
        isTaxApplicable: false,
    },
    {
        id: "18",
        firstName: "Mahmoud",
        lastName: "Hesham",
        email: "mahmoud.hesham@superhr.com",
        role: "Full Stack Engineer",
        department: "Engineering",
        status: "Active",
        joinedDate: "2023-08-20",
        currency: "USD",
        salary: 16500,
    },
    {
        id: "19",
        firstName: "Fouad",
        lastName: "AlFarhan",
        email: "fouad.alfarhan@superhr.com",
        role: "Operations Manager",
        department: "Operations",
        status: "Active",
        joinedDate: "2020-11-11",
        currency: "SAR",
        salary: 22000,
    },
    {
        id: "20",
        firstName: "Rayan",
        lastName: "Alburaidi",
        email: "rayan.alburaidi@superhr.com",
        role: "Customer Success",
        department: "Support",
        status: "Active",
        joinedDate: "2022-04-04",
        currency: "SAR",
        salary: 10500,
    },
    {
        id: "21",
        firstName: "Sayed",
        lastName: "Baladoh",
        email: "sayed.baladoh@superhr.com",
        role: "Systems Administrator",
        department: "IT",
        status: "Active",
        joinedDate: "2021-08-08",
        currency: "EGP",
        salary: 14000,
    },
    {
        id: "22",
        firstName: "Karim",
        lastName: "Hamdy",
        email: "karim.hamdy@superhr.com",
        role: "Security Analyst",
        department: "IT",
        status: "Active",
        joinedDate: "2023-07-01",
        currency: "EGP",
        salary: 15000,
    },
    {
        id: "23",
        firstName: "Ahmed",
        lastName: "ElMasry",
        email: "ahmed.elmasry@superhr.com",
        role: "Content Strategist",
        department: "Marketing",
        status: "Active",
        joinedDate: "2022-03-14",
        currency: "EGP",
        salary: 11500,
    },
    {
        id: "24",
        firstName: "Loai",
        lastName: "AlQaud",
        email: "loai.alqaud@superhr.com",
        role: "Legal Counsel",
        department: "Legal",
        status: "Active",
        joinedDate: "2021-09-25",
        currency: "SAR",
        salary: 24000,
    }
];
